PROJECT := can_node
TYPE := exe
ADD_LIBS := stm8s.lib

SOURCES := \
	main.c \
	led.c \
	module.c \
	eestream.c \
	can.c \
	clock.c \
	sysinfo.c \
	onewire.c \
	mod_proto.c \
	mod_switch.c \
	mod_ds18b20.c

include ../build/makedefs
